version: "3"
services: 
  db:
    container_name: db
    image: postgres
    environment:
     - POSTGRES_DB=dev
     - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:10.0.2
    environment:
     - KEYCLOAK_USER=admin
     - KEYCLOAK_PASSWORD=admin
    ports:
      - "8180:8080"
  systemrenda :
    container_name: systemrenda
    image: quarkus/system-rendas-jvm
    ports:
      - "8080:8080"
    links: 
      - db:db
    